name: ItemActions
version: ${project.version}
main: net.bitbylogic.itemactions.ItemActions
api-version: 1.19
authors: [ BitByLogic ]
depend: [ APIByLogic ]
description: Give items a new purpose, simply.
commands:
  itemactions:
    aliases: [ "ia" ]
    description: "Reload the plugin or give players action items!"
