name: ItemActions
version: ${project.version}
main: net.justugh.ia.ItemActions
api-version: 1.16
authors: [ Justugh ]
depend: [ JustAPI ]
description: Give items a new purpose, simply.
website: www.justugh.net
commands:
  itemactions:
    aliases: [ "ia" ]
    description: "Reload the plugin or give players action items!"
